<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['navigation'] = array(
    'index'=>array(
        'title'=>'首页',
        'menu'=>array(
            'index'=>'用户中心',
            'catalog'=>'分类管理',
            'assist'=>'页面设置',
            'setup'=>'系统设置',
        )
    ),
    'article'=>array(
        'title'=>'文章管理',
        'menu'=>array(
            'article'=>'文章管理',
        )
    ),
    'admin'=>array(
        'title'=>'权限管理',
        'menu'=>array(
            'admin'=>'用户管理',
            'groups'=>'用户组管理'
        )
    ),
	'banner'=>array(
        'title'=>'首页BANNER',
        'menu'=>array(
            'banner'=>'首页BANNER',
        ),
    ),
	'product'=>array(
        'title'=>'产品管理',
        'menu'=>array(
            'product'=>'产品管理',
            'product_type'=>'系列管理',
            'tag'=>'标签管理',
            'tag_type'=>'标签类别管理',
        ),
    ),
	'news'=>array(
        'title'=>'新闻动态',
        'menu'=>array(
            'news'=>'新闻动态',
        ),
    ),
	'video'=>array(
        'title'=>'视频管理',
        'menu'=>array(
            'video'=>'视频管理',
        ),
    ),
	'shop'=>array(
        'title'=>'门店管理',
        'menu'=>array(
            'shop'=>'门店管理',
        ),
    ),
);